OPENQASM 3.0;
include "stdgates.inc";
gate clshift _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3 {
  cu(pi/2, 0, pi, 0) _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_2;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  U(0, 0, pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, -pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  U(0, 0, pi/8) _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  U(0, 0, -pi/8) _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  U(0, 0, -pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cu(pi/2, 0, pi, 0) _gate_q_0, _gate_q_1;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  p(pi/8) _gate_q_0;
}
gate crshift _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3 {
  cu(pi/2, 0, pi, 0) _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_2, _gate_q_1;
  U(0, 0, pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, -pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  U(0, 0, pi/8) _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  U(0, 0, -pi/8) _gate_q_3;
  cx _gate_q_0, _gate_q_3;
  U(0, 0, -pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  U(0, 0, pi/8) _gate_q_2;
  cx _gate_q_0, _gate_q_2;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  U(0, 0, pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  U(0, 0, -pi/8) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  cu(pi/2, 0, pi, 0) _gate_q_0, _gate_q_1;
  ccx _gate_q_0, _gate_q_3, _gate_q_2;
  cx _gate_q_0, _gate_q_3;
  p(pi/8) _gate_q_0;
}
bit[3] out;
qubit[1] dir;
qubit[3] pos;
out[0] = measure pos[0];
out[1] = measure pos[1];
out[2] = measure pos[2];
while (out == 0) {
  h dir[0];
  x dir[0];
  clshift dir[0], pos[0], pos[1], pos[2];
  x dir[0];
  crshift dir[0], pos[0], pos[1], pos[2];
  out[0] = measure pos[0];
  out[1] = measure pos[1];
  out[2] = measure pos[2];
}
